[package]
name = "image-converters"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
bytemuck = { version = "1.14.3", features = ["derive", "extern_crate_std"] }
num = "0.4.1"
num-traits = "0.2.18"
num_enum = "0.7.2"
